Feature/add groups frontend
ESGI-WEB/together pull request #40
Opened 2024-05-19 14:28 UTC by mlaurie

2024-05-28 15:31 UTC, Wadoux-Nicolas requested changes

2024-05-28 15:31 UTC, Wadoux-Nicolas commented on front/lib/groups/groups_screen.dart
> +                  return Positioned.fill(
Column plutot que positioned, sinon kiffer va pas kiffer

2024-05-28 15:31 UTC, Wadoux-Nicolas commented on front/lib/groups/groups_screen.dart
> +              bottom: 16.0,
Column plutot que positioned, sinon kiffer va pas kiffer

2024-05-28 15:31 UTC, Wadoux-Nicolas commented on front/lib/login/blocs/login_bloc.dart
> +import '../../core/services/user_services.dart';
absolut vodka

2024-05-29 11:48 UTC, Quozul commented on back/controllers/group_controller.go
> +	group, err := c.GroupService.GetGroupById(uint(groupID))
Ça me sera aussi utile, sauf que je pourrais pas utiliser un middleware dans mon cas
Il faudrait donc faire un middleware qui appelle un service, comme ça je peux aussi l'utiliser

2024-05-29 12:29 UTC, Wadoux-Nicolas approved these changes

2024-05-29 12:30 UTC, merged