:feat: dropdown eventType
ESGI-WEB/together pull request #60
Opened 2024-05-30 14:37 UTC by Teyo01

2024-06-04 11:37 UTC, mlaurie requested changes

2024-06-04 11:37 UTC, mlaurie commented on front/lib/event/create_event_screen.dart
> +                    const InputDecoration(labelText: 'Type d\'événement'),
Tu kiff faire ça mdr mais autant mettre `"Type d'événement"`

2024-06-04 11:37 UTC, mlaurie commented on front/lib/event/create_event_screen.dart
> +  int groupId = 0;
Depuis quelle heure tu initialises le groupId à 0 ? mdrr
Faut éviter de faire ça ça peut cause de gros souci

2024-06-04 11:37 UTC, mlaurie commented on front/lib/event/create_event_screen.dart
> +        SnackBar(content: Text('Failed to load event types: $e')),
En français les messages d'erreur dans le front

2024-06-04 11:37 UTC, mlaurie commented on front/lib/event/create_event_screen.dart
> +                    return 'Veuillez sélectionner un type d\'événement';
Same

2024-06-04 11:37 UTC, mlaurie commented on front/lib/event/event_screen.dart
> +  static const String routeName = 'events';
Non, là c'est `event` puisque c'est l'écran d'un seul événement ?

2024-06-04 11:37 UTC, mlaurie commented on front/lib/go_router/go_router.dart
> -  // errorBuilder: (context, state) => ErrorScreen(state.error),
C'est po gentil d'avoir enlevé ça

2024-06-05 13:15 UTC, Wadoux-Nicolas requested changes

2024-06-05 13:15 UTC, Wadoux-Nicolas commented on front/lib/core/models/event_type.dart
> +      name: json['Name'],
faut mettre des json dans le modèle bakc pour renvoyer name au lieu de Name

2024-06-05 14:52 UTC, Wadoux-Nicolas approved these changes

2024-06-05 16:02 UTC, merged