Autocomplete address and get latitude longitude + finish event type
ESGI-WEB/together pull request #72
Opened 2024-06-11 20:42 UTC by Teyo01

2024-06-12 07:44 UTC, Quozul commented on front/lib/event/create_event_screen/create_event_screen.dart
> +        SnackBar(content: Text('Failed to load addresses: $e')),
Message a écrire en français

2024-06-13 16:39 UTC, Wadoux-Nicolas requested changes

2024-06-13 16:39 UTC, Wadoux-Nicolas commented on front/lib/event/create_event_screen/create_event_screen.dart
> +        SnackBar(content: Text('Failed to load addresses: $e')),
Y'en a plusieurs dans le fichier

2024-06-13 16:39 UTC, Wadoux-Nicolas commented on front/lib/event/create_event_screen/create_event_screen.dart
> +            '${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}';
Faut utilise dateformat plutot

2024-06-13 16:39 UTC, Wadoux-Nicolas commented on front/lib/event/create_event_screen/create_event_screen.dart
> +            '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}';
Faut utilise dateformat plutot

2024-06-16 11:00 UTC, Wadoux-Nicolas approved these changes

2024-06-16 11:00 UTC, merged